### ISSUE TITLE
Error report: OpenMP/"Programme terminated, error message displayed"

### ISSUE THREAD

**Issue by gatilhocroc** [faker2048/youtube-faster-whisper#4]
Hello, here is the error message in question that was displayed: "*OMP: Error #15*: Initialisation of libiomp5md.dll, but libiomp5md.dll has already been initialised.
OMP: Note This means that multiple copies of the OpenMP runtime environment have been linked into the programme. This is dangerous as it can affect performance or lead to incorrect results. It is best to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in a library. As an unsafe, unsupported and undocumented workaround, you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow further execution of the programme, but this may lead to crashes or give incorrect results unnoticed. Further information can be found at http://www.intel.com/software/products/support/."

> is translated.

To help you resolve the error, I have additional information you may need:

Operating system: Windows 11 Programme version: **newest** 

To reproduce the error, follow these steps:

- [ ] Open the program and ```[ytws t -f "bla" -m model].```

| | | |
|:-|:------------:|-:|
||Thank you for your prompt help. We are looking forward to having the problem fixed as soon as possible so that we can utilise the full potential of the program.||

cuhf

**Comment by faker2048** [comment]
try
```
windows
set KMP_DUPLICATE_LIB_OK=True
linux
export KMP_DUPLICATE_LIB_OK=True
```
ref:
https://community.anaconda.cloud/t/omp-error-15-initializing-libiomp5md-dll-but-found-libiomp5-already-initialized/48993/2

**Comment by gatilhocroc** [comment]
Thank you very much!

And to the problem, I have since added the text part to the main pythonfile with this reply from 18 November at some point. to SO-->Web-["Link"](https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial) tycu
